link_name: "massage_tool"  # tcp robot link
wrench:
  force: [0.0, -10.0, -10.0]    # Force in Newtons [Fx, Fy, Fz]
  torque: [0.0, -10.0, -10.0]    # Torque in Nm [Tx, Ty, Tz]
publish_rate: 10.0  # Rate in Hz