# Sliding State
lambda_0: [2.5, 7.25, 7.25]     # fixed coeff for position error contribution in sliding state
# Coeff for smc switching torque tanh function
gamma_h: [0.8, 0.8, 0.8]       # fixed coeff for tanh
# PD-Dynamic fixed parameters
k_p: [16.0, 80.0, 60.0]           # P-gain for feedforward term in dyn(smooth) torque signal
k_d: [8.0, 8.0, 8.0]           # D-gain for feedforward term in dyn(smooth) torque signal
d_c: [0.1, 1.0, 1.0]           # Damping coeff term in dyn(smooth) torque signal (should be equal or close to xacro coeffs in joints)
f_c: [2.0, 10.0, 10.0]           # Friction coeff term in dyn(smooth) torque signal (should be equal or close to xacro coeffs in joints)
# Factor that sets the weight of VSS2 coefficients (the "<" in p.305 "Robot Manipulator Control-Theory and Practice")
w_margin: 1.1    # must be > 1!
# SMC control vector coefficients' fixed parameters
ki: [12.0, 12.0, 12.0]
pi_limit: 25.0      # max: 25 !
qi_limit: 50.0
#pi_factor: 5.0     # || inv(Lambda) || will be used in run-time 
#qi_factor: 5.0     # || inv(Lambda) || will be used in run-time 