# Sliding State
lambda_0: [17.5, 17.50, 17.5]     # fixed coeff for position error contribution in sliding state
# Coeff for smc switching torque tanh function
gamma_h: [0.95, 0.95, 0.95]       # fixed coeff for tanh
# PD-Dynamic fixed parameters
k_p: [20.0, 20.0, 20.0]           # P-gain for feedforward term in dyn(smooth) torque signal
k_d: [10.0, 10.0, 10.0]           # D-gain for feedforward term in dyn(smooth) torque signal
d_c: [10.0, 15.0, 10.0]           # Damping coeff term in dyn(smooth) torque signal (should be equal or close to xacro coeffs in joints)
f_c: [20.0, 20.0, 20.0]           # Friction coeff term in dyn(smooth) torque signal (should be equal or close to xacro coeffs in joints)
# Factor that sets the weight of VSS2 coefficients (the "<" in p.305 "Robot Manipulator Control-Theory and Practice")
w_margin: 1.5    # must be > 1!
# SMC control vector coefficients' fixed parameters
ki: [1.0, 1.0, 1.0]
pi_limit: 10.0
qi_limit: 10.0
#pi_factor: 5.0     # || Lambda || will be used in run-time 
#qi_factor: 5.0     # || Lambda || will be used in run-time 