lambda_0: [10.0, 10.0, 10.0]    # fixed coeff for position error contribution in sliding state
eta_0: [15.0, 5.0, 5.00]       # adaptive smc coeff for "sign(s)"" contribution is smc torque signal
epsilon_0: [7.0, 10.0, 10.00]  # adaptive smc coeff for "s" contribution in smc torque signal
alpha: [0.05, 0.05, 0.05]     # fixed coeff for adaptive eta
beta: [0.05, 0.05, 0.05]      # fixed coeff for adaptive epsilon
gamma_h: [0.95, 0.95, 0.95]      # fixed coeff for tanh
k_p: [125.0, 125.0, 125.0]    # P-gain for feedforward term in dyn(smooth) torque signal
k_d: [25.0, 25.0, 25.0]       # D-gain for feedforward term in dyn(smooth) torque signal
d_c: [1.0, 1.0, 1.0]          # Damping coeff term in dyn(smooth) torque signal (should be equal or close to xacro coeffs in joints)
f_c: [40.0, 40.0, 40.0]          # Friction coeff term in dyn(smooth) torque signal (should be equal or close to xacro coeffs in joints)