positions:  # joint angles {j1,j2,j3} in [rad]
  position: [0.45, 0.05, 0.30]   # initial:  

velocities:  # joint velocities {j1,j2,j3} in [rad/s]
  velocity: [0.0000, 0.0000, 0.0000]

accelerations:  # joint accelerations {j1,j2,j3} in [rad/s2]
  acceleration: [0.0000, 0.0000, 0.0000]
