positions: # joint angles {j1,j2,j3} in [rad]
  names: [position_0,position_1,position_2]
  position_0: [0.1572, -0.2925, 0.5708] 
  position_1: [0.0363, -0.1290, 0.5746] 
  position_2: [-0.0508, -0.1685, 0.5756] 
velocities: # joint velocities {j1,j2,j3} in [rad/s]
  names: [velocity_0,velocity_1,velocity_2]
  velocity_0: [0.0000, 0.0000, 0.0000]
  velocity_1: [0.0000, 0.0000, 0.0000]
  velocity_2: [0.0000, 0.0000, 0.0000]
accelerations: # joint accelerations {j1,j2,j3} in [rad/s2]
  names: [acceleration_0,acceleration_1,acceleration_2]
  acceleration_0: [0.0000, 0.0000, 0.0000]   
  acceleration_1: [0.0000, 0.0000, 0.0000]  
  acceleration_2: [0.0000, 0.0000, 0.0000] 