positions:  # joint angles {j1,j2,j3} in [rad]
  position: [0.42, 0.3866, 0.37]   # initial:  0.4178, 0.6866, 0.3692

velocities:  # joint velocities {j1,j2,j3} in [rad/s]
  velocity: [0.0000, 0.0000, 0.0000]

accelerations:  # joint accelerations {j1,j2,j3} in [rad/s2]
  acceleration: [0.0000, 0.0000, 0.0000]
