positions:  # tcp cartesian positions {px,py,pz} in [m]
  position: [0.4087, -0.2924, 0.2631]   # initial:  0.3302, -0.3532, 0.3230

velocities:  # tcp cartesian velocities {vx,vy,vz} in [m/s]
  velocity: [0.0000, 0.0000, 0.0000]

accelerations:  # tcp cartesian accelerations {ax,ay,az} in [m/s2]
  acceleration: [0.0000, 0.0000, 0.0000]
