cartesian_positions:  # tcp cartesian positions {px,py,pz} in [m]
  position: [0.2103, -0.3779, 0.3300]   # initial:  [0.1215, -0.3748, 0.3797]  # previous try (working): [0.1934, -0.3792, 0.3398]

cartesian_velocities:  # tcp cartesian velocities {vx,vy,vz} in [m/s]
  velocity: [0.0000, 0.0000, 0.0000]

cartesian_accelerations:  # tcp cartesian accelerations {ax,ay,az} in [m/s2]
  acceleration: [0.0000, 0.0000, 0.0000]
